LOCAL_PATH := device/xiaomi/santoni

FOX_VERSION := 12.1
FOX_BUILD_TYPE := Unofficial

OF_SCREEN_H := 1280
OF_STATUS_BAR_PADDING := 55

FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER := 1
OF_USE_GREEN_LED := 1
OF_FLASHLIGHT_ENABLE := 1
OF_FLASHLIGHT_ENABLE_USER_PATH := 1

FOX_REPLACE_BUSYBOX_PS := 1
FOX_USE_SED_BINARY := 1
FOX_USE_TAR_BINARY := 1
FOX_USE_BASH_SHELL := 1
